server:
  tomcat:
    max-http-header-size: 8192
spring:
#  profiles:
#    active: dev
  application:
    name: hobart-sample-server
#  boot:
#    admin:
#      username: ${security.user.name:admin}
#      password: ${security.user.password:admin}
#  redis:
#    host: ${spring.redis.host:paascloud-db-redis}
#    password: ${spring.redis.password:123456}
#    port: ${spring.redis.port:6379}
#    timeout: ${spring.redis.timeout:0}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
mybatis:
    type-aliases-package: com.hobart.sample.domain.model
    mapper-locations: classpath:mapper/*.xml
mapper:
    mappers:
        - com.hobart.sample.common.mybatis.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql