spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
#  profiles:
#    active: dev
  application:
    name: hobart-sample-server
#  freemarker: 
#    template-loader-path: classpath:/templates
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: false
#    expose-session-attributes: false
#    request-context-attribute: request
#    spring.freemarker.suffix: .ftl
#  boot:
#    admin:
#      username: ${security.user.name:admin}
#      password: ${security.user.password:admin}
  redis:
    host: 127.0.0.1
#    password: ${spring.redis.password:}
    port: 6379
    timeout: 60
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
mybatis:
    type-aliases-package: com.hobart.sample.domain.model
    mapper-locations: classpath:mapper/*.xml
    configuration: 
        map-underscore-to-camel-case: true
mapper:
    mappers:
        - com.hobart.sample.common.mybatis.MyMapper
    not-empty: false
    identity: MYSQL
#    order: BEFORE
#    before: true
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging.level.com.hobart.sample: debug
#logging.level.org.springframework.web: debug